#!/bin/bash

PWFILE=${PGDATA}/../pwfile

if [ ! -f PWFILE ]; then

  # create actual datadir
  mkdir -p ${PGDATA}
  chown -Rf postgres:postgres /var/lib/postgresql
  chmod 0700 ${PGDATA}

  # generate the password & add it to the pwfile
  install -m 0600 -g postgres -o postgres /dev/null ${PWFILE}
  echo "${PASSWORD:-`pwgen -s 20 1`}" > ${PWFILE}

  # build initial db cluster
  su -c "/usr/lib/postgresql/9.3/bin/initdb \
    --pwfile=${PWFILE} \
    --username=postgres \
    --encoding=unicode \
    --auth=trust > /dev/null" postgres

  # disable SSL
  sed "s/ssl = true/#ssl = true/" -i ${PGDATA}/postgresql.conf

  # listen on all addresses
  sed -ri "s/^#(listen_addresses\s*=\s*)\S+/\1'*'/" ${PGDATA}/postgresql.conf

  # add the pg_hba.conf entries
  echo -e "local\tall\tpostgres\t\ttrust" > ${PGDATA}/pg_hba.conf
  echo -e "host\tall\tall\t\tall\tmd5" >> ${PGDATA}/pg_hba.conf

  # log the postgres user/password
  echo "PGUSER=postgres"
  echo "PGPASSWORD=`cat ${PWFILE}`"
fi

echo "Starting `/usr/lib/postgresql/9.3/bin/postgres -V`..."
exec su -c "/usr/lib/postgresql/9.3/bin/postgres -D $PGDATA -c config_file=$PGDATA/postgresql.conf" postgres
